### ISSUE TITLE
Correct links pointing to old site

### ISSUE THREAD

**Issue by alambike** [prefapp/formacion#10]
## Motivation
Some links in Kubernetes course points to old site, like:

https://prefapp.github.io/formacion/cursos/kubernetes/#/./00_actividades/03_modulo_3?id=mellorando-a-nosa-aplicaci%c3%b3n

 > documentación sobre "[avanzando en Kubernetes](https://formacion.4eixos.com/k8s/tema3)"
 > da tarefa [2.3](https://formacion.4eixos.com/k8s/actividades/2/correndo_a_nosa_primeira_aplicacin_en_kubernetes.html).

## Acceptance criteria

- All links in Kubernetes course, pointing to the old site (https://formacion.4eixos.com), corrected to point to internal links
- All links in Docker course, pointing to old site, corrected to point to internal links

**Comment by gustavoborragan** [comment]
@alambike, tarea asignada a @AlbertoFemenias.
