### ISSUE TITLE
Add configuration to the terraform course

### ISSUE THREAD

**Issue by AinhoMD** [prefapp/formacion#172]
I suggest adding this configuration to the terraform course. It's useful to avoid deprecated attributes by choosing a determined version.
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "5.48.0"
    }
  }
}

**Comment by yvidalv** [comment]
Ok, let's do this. 

I suggest to try to execute all the examples on the course with the last version of the API and fix any possible warning messages.
