### ISSUE TITLE
Modify kubertenes course

### ISSUE THREAD

**Issue by pablosanchezpaz** [prefapp/formacion#79]
Change kubernetes section.
 - Certificates: Place it as optional and more interesting.
 - Statefulsets: Add practice.
 - HPA(Horizontal pod autoscaler): Add practice.

**Comment by frmadem** [comment]
# Autoescaling pods

This section could be named: "Adaptandose dinámicamente á carga: o HPA"

## Contents

It should explain what an [HPA](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/) is and its purpose. 

Also it should have a guided practice:

1. An application is deployed
2. An HPA is established to control the number of replicas
3. A surge in load occurs. 
4. The pod numbers is adjusted. 

## Preparations

1. A CPU intensive app should be used. Something that uses a lot of CPU/RAM depending of the number of requests. 
2. For controling the requests we could use [locust](https://locust.io/) a python application.
