### ISSUE TITLE
Add lesson 5 to Docker course

### ISSUE THREAD

**Issue by alambike** [prefapp/formacion#9]
## Motivation

The lesson 5 in Docker course, about Docker Swarm, is missing, we want to bring it here.

## Acceptance criteria
- lesson 5 available in the Docker course

**Comment by gustavoborragan** [comment]
@alambike, tarea asignada a @pablosanchezpaz.

**Comment by pablosanchezpaz** [comment]
Lesson 5 added.  [Here](https://prefapp.github.io/formacion/cursos/docker/#/./05_docker_swarm/01_o_docker_swarm)
